#!/bin/bash
#
#*****************************************************************************
# test (xpc/tests)
#-----------------------------------------------------------------------------
##
# \file       	test
# \library    	xpc
# \author     	Chris Ahlstrom
# \date       	2012-06-20
# \updates     2012-06-20
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#     Runs some combinations of options that can have erroneous side-effects
#     that break the unit tests.
#
# \todo
#     -  We should work test coverage into this script as well.
#
#-----------------------------------------------------------------------------

./test_script

#*****************************************************************************
# test (xpc/tests)
#------------------------------------------------------------------------------
# Local Variables:
# End:
#-----------------------------------------------------------------------------
# vim: ts=3 sw=3 ft=sh
#----------------------------------------------------------------------------
